### ISSUE TITLE
'Run cp -R static/* output` Step Fails due to Non-Existent Directory

### ISSUE THREAD

**Issue by barndawgie** [esphome/workflows#60]
I'm not sure if something has changed with underlying programs but if I run the publish workflow from this repo, it fails saying `cp: cannot stat 'static/*': No such file or directory`

I can't figure out where this "static" directory is supposed to be created.

Example failed workflow (with debug logging):
https://github.com/barndawgie/esphome-econet/actions/runs/6758181927/job/18369604462

**Comment by nliaudat** [comment]
same error. 
Any update ? 

Regards

**Comment by barndawgie** [comment]
> same error. 
> 
> 
> 
> 
> 
> ```
> 
> Run cp -R static/* output
> 
>   cp -R static/* output
> 
>   shell: /usr/bin/bash -e {0}
> 
> cp: cannot stat 'static/*': No such file or directory
> 
> Error: Process completed with exit code 1.
> 
> ```
> 
> 
> 
> Any update ? 
> 
> 
> 
> Regards

I think I ended up moving to a different action but regardless if you take a look at the esphome-EcoNet repo we have a working publishing workflow you can use instead of this.

**Comment by stephenpapierski** [comment]
I found https://github.com/esphome/esphome-project-template which makes a lot more sense as a starting point. It uses this workflow and it has a static directory to host the GitHub Pages content.

**Comment by jesserockz** [comment]
Sorry yeah, the publish workflow made a lot of assumptions as I originally made it for internal use, but then it got more popular. 
We are in the process of moving ESPHome firmwares to an entirely new workflow in this repo (build.yml) which stores the files in Cloudflare R2 so we have better control over versioning.
